const router = require("express").Router()
const HomeController = require("../controllers/home.controller")
const authRoutes = require("./auth.routes")
const categoriesRoutes = require("./categories.routes")
const collectionsRoutes = require("./collections.routes")
const brandsRoutes = require("./brands.routes")
const testimonialsRoutes = require("./testimonials.routes")
const dealsRoutes = require("./deals.routes")
const contactsRoutes = require("./contacts.routes")
const productsRoutes = require("./products.routes")
const cartRoutes = require("./cart.routes")
const filtersRoutes = require("./filters.routes")
const wishlistRoutes = require("./wishlist.routes")
const comparisonRoutes = require("./comparison.routes")
const reviewsRoutes = require("./reviews.routes")
const configRoutes = require("./config.routes")
const ordersRoutes = require("./orders.routes")
const couponsRoutes = require("./coupons.routes")
const governmentsRoutes = require("./governments.routes")
const adminRoutes = require("./admin")

router.get("/", HomeController.handle)
router.use("/auth", authRoutes)
router.use("/categories", categoriesRoutes)
router.use("/collections", collectionsRoutes)
router.use("/brands", brandsRoutes)
router.use("/testimonials", testimonialsRoutes)
router.use("/deals", dealsRoutes)
router.use("/contacts", contactsRoutes)
router.use("/products", productsRoutes)
router.use("/cart", cartRoutes)
router.use("/filters", filtersRoutes)
router.use("/wishlist", wishlistRoutes)
router.use("/comparison", comparisonRoutes)
router.use("/reviews", reviewsRoutes)
router.use("/config", configRoutes)
router.use("/orders", ordersRoutes)
router.use("/coupons", couponsRoutes)
router.use("/governments", governmentsRoutes)
router.use("/admin", adminRoutes)

module.exports = router
